### ISSUE TITLE
Install husky (git hooks) and configurate precommit / prepush

### ISSUE THREAD

**Issue by mateusduraes** [mateusduraes/crawler-br-news#2]
You should install husky and configurate the precommit or / and prepush hook to run tslint.

**Comment by piq9117** [comment]
Hi! I'll take this one. 😃

**Comment by mateusduraes** [comment]
Ok @piq9117, thanks, i'll be waiting the PR.

**Comment by blackpioter** [comment]
Hi there. I had a free moment to setup what you need.
Note: the tslint.json is empty. You need to define the rules or give me some direction on what you need.

**Comment by piq9117** [comment]
looks like he took it ^. I'm out.

**Comment by mateusduraes** [comment]
@piq9117 Yeah, it's ok.
@blackpioter Thank you dude. About the tslint.json, we have some pull requests with that configuration.
